### PR TITLE
fix(readme): corrected cdn badges

### PR DESCRIPTION
**Pull request by y0hami**
Added the official cdn badges instead of renaming shields.io ones 😜

### CODE REVIEW

**Comment by douglasg14b** [comment]
I used the renamed shield.io ones to display the version numbers since JSDeliver does not do that, which is what I was going for.

**Comment by y0hami** [comment]
@douglasg14b I have changed the badges to custom dynamic badges by shields.io. It will pull the latest version number from the jsdelivr and cdnjs APIs.

**Comment by douglasg14b** [comment]
Nice! Only issue I have now is the links to the jsdeliver and cdnjs need to be wrapped back around the badges. (putting the link syntax `[](jsdeliverurl)` around the existing image link syntax works)

How did you create a custom badge to retrieve the jsdeliver version number by the way?

**Comment by y0hami** [comment]
@douglasg14b Links added!

Go to https://shields.io and scroll down to "Your Badge" and there is a section under that called "Dynamic" and you can select a datatype and then query it 😉

**Comment by douglasg14b** [comment]
Well that's neat. Thanks!

**Pull request merged**
